library(package = "AlphaSimR")
source(file = "R/Class-SimParamBee.R")
source(file = "R/Class-Colony.R")
source(file = "R/Class-Colonies.R")
source(file = "R/Functions_L0_auxilary.R")
source(file = "R/Functions_L1_Pop.R")
source(file = "R/Functions_L2_Colony.R")
source(file = "R/Functions_L3_Colonies.R")
