---
title: "AlphaSimRBee"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{AlphaSimRBee}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# L0 functions 

nColonies; input colonies; return n

nCaste; input Colony or Colonies; return n
nQueen
nVirginQueens
nFathers
nWorkers 
nDrones 
nHomDrones

isQueenMated; input Pop, Colony, or Colonies; return logical

getQueensYearOfBirth & getQueensYOB; input Pop, Colony or Colonies; return numeric
getQueensAge

getId; input Colony or Colonies; return character
getLocation; input Colony or Colonies; return numeric or list of numeric

hasSplit; input Colony or Colonies; return logical
hasSwarmed
hasSuperseded
isProductive

SimParamBee
simulateHoneyBeeGenomes TODO

getCsdHaplo; input Pop, Colony or Colonies; return matrix, list of matrix, list of a list of matrix
getCsdGeno

getIbdHaplo; input Pop; return matrix
getQtlHaplo
getQtlGeno
getSegSiteHaplo
getSegSiteGeno
getSnpHaplo
getSnpGeno

getCasteIbdHaplo; input Colony or Colonies; return matrix or list of matrix
getQueensIbdHaplo
getFathersIbdHaplo
getVirginQueensIbdHaplo
getWorkersIbdHaplo
getDronesIbdHaplo
getColonyIbdHaplo; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteQtlHaplo; input Colony or Colonies; return matrix or list of matrix
getQueensQtlHaplo
getFathersQtlHaplo
getVirginQueensQtlHaplo
getWorkersQtlHaplo
getDronesQtlHaplo
getColonyQtlHaplo; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteQtlGeno; input Colony or Colonies; return matrix or list of matrix
getQueensQtlGeno
getFathersQtlGeno
getVirginQueensQtlGeno
getWorkersQtlGeno
getDronesQtlGeno
getColonyQtlGeno; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteSegSiteHaplo; input Colony or Colonies; return matrix or list of matrix
getQueensSegSiteHaplo
getFathersSegSiteHaplo
getVirginQueensSegSiteHaplo
getWorkersSegSiteHaplo
getDronesSegSiteHaplo
getColonySegSiteHaplo; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteSegSiteGeno; input Colony or Colonies; return matrix or list of matrix
getQueensSegSiteGeno
getFathersSegSiteGeno
getVirginQueensSegSiteGeno
getWorkersSegSiteGeno
getDronesSegSiteGeno
getColonySegSiteGeno; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteSnpHaplo; input Colony or Colonies; return matrix or list of matrix
getQueensSnpHaplo
getFathersSnpHaplo
getVirginQueensSnpHaplo
getWorkersSnpHaplo
getDronesSnpHaplo
getColonySnpHaplo; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteSnpGeno; input Colony or Colonies; return matrix or list of matrix
getQueensSnpGeno
getFathersSnpGeno
getVirginQueensSnpGeno
getWorkersSnpGeno
getDronesSnpGeno
getColonySnpGeno; input Colony or Colonies; return list of matrix or list of a list of matrix

getCasteGv; input Colony or Colonies; return vector or list of vector
getQueensGv
getFathersGv
getVirginQueensGv
getWorkersGv
getDronesGv
getColonyGv; input Colony or Colonies; return list of vector or list of a list of vector

getCasteBv; input Colony or Colonies; return vector or list of vector
getQueensBv
getFathersBv
getVirginQueensBv
getWorkersBv
getDronesBv
getColonyBv; input Colony or Colonies; return list of vector or list of a list of vector

getCasteDd; input Colony or Colonies; return vector or list of vector
getQueensDd
getFathersDd
getVirginQueensDd
getWorkersDd
getDronesDd
getColonyDd; input Colony or Colonies; return list of vector or list of a list of vector

# L1 functions

getCaste; input Colony or Colonies; return Pop
getQueen
getFathers
getVirginQueens
getWorkers
getDrones

createFounderDrones; input Pop; return Pop; TODO merge with createDrones?

createWorkers; input Colony; return Pop; TODO work also with Colonies?
createDrones
createVirginQueens

createDCA; input Colony or Colonies; return Pop

pullInd; input Pop; return list of 2 Pop

pullDroneGroupsFromDCA; input Pop; list of n Pop; TODO rename to pullIndGroups?

pullCaste; input Colony or Colonies; return list of Pop and Colony
pullQueen
pullVirginQueens
pullWorkers
pullDrones

crossVirginQueen; input 2 Pop; return Pop

setLocation; input Colony or Colonies; return Colony or Colonies

setQueensYearOfBirth & setQueensYOB; input Pop, Colony, or Colonies; return Pop, Colony, or Colonies

# L2 functions

createColony; input Pop; return Colony

reQueenColony; TODO rename to replaceQueen() to be consistent with other replace functions? Or should this be called setQueen() and it can
  then serve as a way to set a queen for the new colony as well as to set a new queen that replaces the old one?
addVirginQueens; TODO add external virgin queens instead of just generating them from the hive?

addWorkers; input Colony, return Colony; TODO some have Colony in name, some don't!?
addDrones
buildUpColony; TODO use replace* and add* arguments? rename to buildUp()?
replaceWorkers
replaceDrones
removeQueen
removeVirginQueen
removeWorkers
removeDrones
resetEvents
crossColony; TODO rename to cross()? there are many cross() in R, so this won't work
collapseColony; TODO rename to collapse()?
supersedeColony; TODO rename to supersede()?
setPhenoColony; TODO rename to setColonyPheno()?

swarmColony; input Colony, return list of 2 Colony; TODO rename to swarm()?
splitColony; TODO rename to split() (clash with other R func(s))?

# L3 functions

createColonies; input n or Pop; return Colonies; TODO how is this different to createColony?

addColonyToTheColonies; REMOVE input Colones and Colony; return Colonies; TODO rename to addColony() or just add()?
assignColonyToColonies; TODO rename to assignColony() or just assign()?

selectColonies; input Colonies; return Colonies
removeColonies

pullColonies; input Colonies; return list of 2 Colonies

buildUpColonies; input Colonies; return Colonies; TODO rename to buildUp()?
replaceWorkersColonies; TODO merge with replaceWorkers()?
replaceDronesColonies; TODO merge with replaceDrones()?
reQueenColonies; TODO merge with replaceQueen()?
collapseColonies; TODO merge with collapse()?
supersedeColonies; TODO merge with supersede()?

swarmColonies; input Colonies; return list of 2 Colonies; TODO merge with swarm()?
splitColonies; TODO merge with split() (clash with other R func(s))?

crossColonies; input Colonies; return Colonies; TODO merge with cross()? there is many cross() in R, so this won't work
setPhenoColonies; TODO merge with setColonyPheno?

